version: "3.7"
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    restart: always
    hostname: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
      - 15673:15673
      - 1883:1883
      - 15674:15674
      - 15675:15675
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/mnesia

  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: toor
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container:
  rabbitmq_data:

